name: Docusaurus
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#on: [ workflow_dispatch ]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Create local changes and commit
        run: |
          cd docs-site
          yarn
          cd build
          git init
          git add .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "docs: build docs" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: deployed-docs
          force: true
          directory: docs/build
